//! Minimal but structurally-correct APFS space manager.
//!
//! The writer hands `build_spaceman` a description of which container
//! blocks are currently used (the entire prefix from 0 to `next_block`,
//! since we bump-allocate); this module emits:
//!
//! * a `spaceman_phys_t` block with one main-device entry and an inline
//!   array of CIB physical addresses (no CAB indirection — single CIB),
//! * a `chunk_info_block_t` (CIB) containing one `chunk_info_t` per
//!   container chunk,
//! * one allocation-bitmap block per used chunk.
//!
//! Bitmap convention: a set bit means "used"; cleared bits are free.
//! This matches `apfsprogs/mkapfs/spaceman.c` (`bmap_mark_as_used`) and
//! the Apple File System Reference.
//!
//! Layout in the on-disk spaceman_phys_t (offsets from the start of the
//! block, all little-endian; identical to the libfsapfs description):
//!
//! ```text
//!   0..32   obj_phys_t (cksum, oid, xid, type=OBJ_EPHEMERAL|0x0005, subtype=0)
//!  32..48   sm_block_size / sm_blocks_per_chunk / sm_chunks_per_cib / sm_cibs_per_cab
//!  48..96   SD_MAIN spaceman_device_t (48 bytes)
//!  96..144  SD_TIER2 spaceman_device_t (zero for single-device)
//! 144..148  sm_flags
//! 148..152  sm_ip_bm_tx_multiplier
//! 152..160  sm_ip_block_count
//! 160..164  sm_ip_bm_size_in_blocks
//! 164..168  sm_ip_bm_block_count
//! 168..176  sm_ip_bm_base
//! 176..184  sm_ip_base
//! 184..192  sm_fs_reserve_block_count
//! 192..200  sm_fs_reserve_alloc_count
//! 200..240  SFQ_IP    spaceman_free_queue_t (40 bytes)
//! 240..280  SFQ_MAIN  spaceman_free_queue_t
//! 280..320  SFQ_TIER2 spaceman_free_queue_t
//! 320..324  sm_ip_bm_free_head / sm_ip_bm_free_tail (each u16)
//! 324..336  sm_ip_bm_xid_offset / sm_ip_bitmap_offset / sm_ip_bm_free_next_offset
//! 336..340  sm_version (=1)
//! 340..344  sm_struct_size
//! 344..    sm_datazone (two 72-byte allocation-zone arrays, all zero)
//! ```
//!
//! For our minimal images we leave the internal-pool (`sm_ip_*`) and
//! free-queue fields at zero. fsck_apfs implementations that strictly
//! validate the internal pool may still complain; the writer documents
//! this limitation. The chunk bitmaps reflect the writer's true
//! allocations.

use crate::Result;

use super::checksum::fletcher64;

/// `OBJECT_TYPE_SPACEMAN`.
pub(super) const OBJECT_TYPE_SPACEMAN: u32 = 0x0000_0005;
/// `OBJECT_TYPE_SPACEMAN_CIB`.
pub(super) const OBJECT_TYPE_SPACEMAN_CIB: u32 = 0x0000_0007;

/// `OBJ_PHYSICAL`.
const OBJ_PHYSICAL: u32 = 0x4000_0000;
/// `OBJ_EPHEMERAL`.
const OBJ_EPHEMERAL: u32 = 0x8000_0000;

/// Number of blocks one bitmap block can track at `block_size = 4096`.
/// Each byte tracks 8 blocks, so a 4096-byte bitmap covers 32 768
/// blocks. The spec ties this to `sm_blocks_per_chunk = 8 * block_size`.
pub(super) fn blocks_per_chunk(block_size: usize) -> u64 {
    (block_size as u64) * 8
}

/// Number of `chunk_info_t` entries (32 bytes each) that fit in a single
/// CIB block after the 40-byte header.
pub(super) fn chunks_per_cib(block_size: usize) -> u32 {
    ((block_size - 40) / 32) as u32
}

/// Information needed to emit the spaceman.
pub(super) struct SpacemanLayout {
    /// Block size of the container (typically 4096).
    pub block_size: usize,
    /// Total number of blocks in the container.
    pub total_blocks: u64,
    /// XID stamped on every emitted spaceman / CIB / bitmap block.
    pub xid: u64,
    /// Ephemeral oid for the spaceman header. Matches what the NXSB
    /// publishes in `nx_spaceman_oid` and what the checkpoint map
    /// resolves to the spaceman's physical block.
    pub spaceman_oid: u64,
    /// Physical address of the (sole) chunk_info_block.
    pub cib_paddr: u64,
    /// Physical addresses of the per-chunk bitmap blocks. One entry per
    /// chunk (in order). Empty bitmaps may be elided by passing
    /// `0` here; we always emit a full bitmap for chunk 0.
    pub bitmap_paddrs: Vec<u64>,
    /// All block ranges considered used by the writer. Inclusive start,
    /// exclusive end. The bitmap is generated by ORing the bit for each
    /// block in every range.
    pub used_ranges: Vec<(u64, u64)>,
}

/// Emitted spaceman artifact: the three (or more) block payloads.
pub(super) struct EmittedSpaceman {
    pub spaceman_block: Vec<u8>,
    pub cib_block: Vec<u8>,
    /// One bitmap-block payload per chunk. `bitmap_blocks[i]` is the
    /// content to write at `layout.bitmap_paddrs[i]` (if that address is
    /// non-zero).
    pub bitmap_blocks: Vec<Vec<u8>>,
}

/// Build the spaceman_phys, the single chunk_info_block, and one bitmap
/// block per chunk. The caller is responsible for writing each block at
/// the address recorded in `layout`.
pub(super) fn build_spaceman(layout: &SpacemanLayout) -> Result<EmittedSpaceman> {
    let bs = layout.block_size;
    if bs < 512 || !bs.is_power_of_two() {
        return Err(crate::Error::InvalidArgument(format!(
            "apfs spaceman: implausible block size {bs}"
        )));
    }
    let bpc = blocks_per_chunk(bs);
    let chunks: u64 = layout.total_blocks.div_ceil(bpc);
    let cpc = chunks_per_cib(bs);
    if chunks as u32 > cpc {
        return Err(crate::Error::Unsupported(format!(
            "apfs spaceman: {chunks} chunks would overflow a single CIB \
             (max {cpc}); CAB layer not implemented"
        )));
    }
    if layout.bitmap_paddrs.len() != chunks as usize {
        return Err(crate::Error::InvalidArgument(format!(
            "apfs spaceman: caller supplied {} bitmap paddrs for {} chunks",
            layout.bitmap_paddrs.len(),
            chunks,
        )));
    }

    // ---- Per-chunk bitmaps ------------------------------------------
    let mut bitmap_blocks: Vec<Vec<u8>> = Vec::with_capacity(chunks as usize);
    let mut free_total: u64 = 0;
    let mut free_per_chunk: Vec<u32> = Vec::with_capacity(chunks as usize);
    for chunk_idx in 0..chunks {
        let mut bmap = vec![0u8; bs];
        let chunk_start = chunk_idx * bpc;
        let chunk_end = ((chunk_idx + 1) * bpc).min(layout.total_blocks);
        let chunk_blocks = (chunk_end - chunk_start) as u32;
        // Mark every used block inside this chunk's bitmap.
        for &(rs, re) in &layout.used_ranges {
            let lo = rs.max(chunk_start);
            let hi = re.min(chunk_end);
            for b in lo..hi {
                let bit = (b - chunk_start) as usize;
                bmap[bit / 8] |= 1 << (bit % 8);
            }
        }
        // Mark "beyond end of container" bits as used so the chunk's
        // free count is exactly free_blocks_in_chunk and fsck doesn't
        // claim them as free.
        for bit in chunk_blocks..(bpc as u32) {
            let bit = bit as usize;
            bmap[bit / 8] |= 1 << (bit % 8);
        }
        // Count free blocks in this chunk.
        let mut used: u32 = 0;
        for &(rs, re) in &layout.used_ranges {
            let lo = rs.max(chunk_start);
            let hi = re.min(chunk_end);
            if hi > lo {
                used += (hi - lo) as u32;
            }
        }
        let free = chunk_blocks - used;
        free_per_chunk.push(free);
        free_total += free as u64;
        bitmap_blocks.push(bmap);
    }

    // ---- Chunk-info-block (CIB) -------------------------------------
    let mut cib = vec![0u8; bs];
    // obj_phys
    cib[8..16].copy_from_slice(&layout.cib_paddr.to_le_bytes());
    cib[16..24].copy_from_slice(&layout.xid.to_le_bytes());
    cib[24..28].copy_from_slice(&(OBJECT_TYPE_SPACEMAN_CIB | OBJ_PHYSICAL).to_le_bytes());
    // subtype stays zero.
    // cib_index = 0
    cib[32..36].copy_from_slice(&0u32.to_le_bytes());
    // cib_chunk_info_count
    cib[36..40].copy_from_slice(&(chunks as u32).to_le_bytes());
    let chunk_info_base = 40usize;
    for (chunk_idx, (&free_in_chunk, &bmap_paddr)) in free_per_chunk
        .iter()
        .zip(layout.bitmap_paddrs.iter())
        .enumerate()
    {
        let off = chunk_info_base + chunk_idx * 32;
        let chunk_start = (chunk_idx as u64) * bpc;
        let chunk_end = (chunk_start + bpc).min(layout.total_blocks);
        let chunk_blocks = (chunk_end - chunk_start) as u32;
        // ci_xid
        cib[off..off + 8].copy_from_slice(&layout.xid.to_le_bytes());
        // ci_addr — block number of the first block in this chunk
        cib[off + 8..off + 16].copy_from_slice(&chunk_start.to_le_bytes());
        // ci_block_count
        cib[off + 16..off + 20].copy_from_slice(&chunk_blocks.to_le_bytes());
        // ci_free_count
        cib[off + 20..off + 24].copy_from_slice(&free_in_chunk.to_le_bytes());
        // ci_bitmap_addr — physical address of the bitmap block for
        // this chunk, or zero if the chunk has no bitmap (hole — every
        // bit would have been zero anyway).
        cib[off + 24..off + 32].copy_from_slice(&bmap_paddr.to_le_bytes());
    }
    sign_block(&mut cib);

    // ---- Spaceman header --------------------------------------------
    let mut sm = vec![0u8; bs];
    // obj_phys
    sm[8..16].copy_from_slice(&layout.spaceman_oid.to_le_bytes());
    sm[16..24].copy_from_slice(&layout.xid.to_le_bytes());
    sm[24..28].copy_from_slice(&(OBJECT_TYPE_SPACEMAN | OBJ_EPHEMERAL).to_le_bytes());
    // subtype stays zero.
    // sm_block_size
    sm[32..36].copy_from_slice(&(bs as u32).to_le_bytes());
    // sm_blocks_per_chunk
    sm[36..40].copy_from_slice(&(bpc as u32).to_le_bytes());
    // sm_chunks_per_cib
    sm[40..44].copy_from_slice(&cpc.to_le_bytes());
    // sm_cibs_per_cab — at the same arithmetic per CIB structure; doesn't
    // matter while we keep cab_count=0 but record a sensible figure.
    let cibs_per_cab = ((bs - 40) / 8) as u32;
    sm[44..48].copy_from_slice(&cibs_per_cab.to_le_bytes());

    // SD_MAIN spaceman_device_t (48 bytes) at offset 48
    sm[48..56].copy_from_slice(&layout.total_blocks.to_le_bytes()); // sm_block_count
    sm[56..64].copy_from_slice(&chunks.to_le_bytes()); // sm_chunk_count
    sm[64..68].copy_from_slice(&1u32.to_le_bytes()); // sm_cib_count = 1
    sm[68..72].copy_from_slice(&0u32.to_le_bytes()); // sm_cab_count = 0
    sm[72..80].copy_from_slice(&free_total.to_le_bytes()); // sm_free_count
    // sm_addr_offset: byte offset (relative to start of spaceman block)
    // where the inline CIB-address array begins. We place it at offset
    // 1492 (just past the data-zone arrays) — the same region mkapfs
    // uses for the "trailing data" payload.
    let cib_addr_off: u32 = 1492;
    sm[80..84].copy_from_slice(&cib_addr_off.to_le_bytes());
    // reserved bytes stay zero.

    // SD_TIER2 left zero at offset 96.

    // sm_flags = SM_FLAG_VERSIONED so we publish sm_version reliably.
    sm[144..148].copy_from_slice(&1u32.to_le_bytes());
    // sm_ip_* fields all zero (no internal pool tracked).
    // SFQ_IP / SFQ_MAIN / SFQ_TIER2 all zero (empty queues).
    // sm_version
    sm[336..340].copy_from_slice(&1u32.to_le_bytes());
    // sm_struct_size — total in-use size of the on-disk struct. We say
    // it ends right after the inline CIB-address array.
    let struct_size = (cib_addr_off as usize) + 8 * (chunks as usize);
    sm[340..344].copy_from_slice(&(struct_size as u32).to_le_bytes());

    // Inline single-CIB address array at sm_addr_offset.
    let off = cib_addr_off as usize;
    if off + 8 > bs {
        return Err(crate::Error::Unsupported(format!(
            "apfs spaceman: block size {bs} too small for inline CIB addr array"
        )));
    }
    sm[off..off + 8].copy_from_slice(&layout.cib_paddr.to_le_bytes());

    sign_block(&mut sm);

    Ok(EmittedSpaceman {
        spaceman_block: sm,
        cib_block: cib,
        bitmap_blocks,
    })
}

/// Fletcher-64 sign helper (duplicated from `write.rs` so this module
/// is self-contained).
fn sign_block(buf: &mut [u8]) {
    let cksum = fletcher64(buf);
    buf[0..8].copy_from_slice(&cksum.to_le_bytes());
}

// ---- decoders for tests ----

/// Lightweight decoded view of a spaceman header used by lib tests.
#[cfg(test)]
#[derive(Debug)]
pub(super) struct DecodedSpaceman {
    pub block_size: u32,
    pub blocks_per_chunk: u32,
    pub main_block_count: u64,
    pub main_chunk_count: u64,
    pub main_cib_count: u32,
    pub main_cab_count: u32,
    pub main_free_count: u64,
    pub cib_paddr: u64,
}

/// Decode a freshly emitted spaceman block. Returns an error if the
/// type bits or version look wrong.
#[cfg(test)]
pub(super) fn decode_spaceman(buf: &[u8]) -> Result<DecodedSpaceman> {
    if buf.len() < 344 {
        return Err(crate::Error::InvalidImage(
            "apfs spaceman: block too short".into(),
        ));
    }
    let otype = u32::from_le_bytes(buf[24..28].try_into().unwrap());
    if otype & 0x0000_ffff != OBJECT_TYPE_SPACEMAN {
        return Err(crate::Error::InvalidImage(format!(
            "apfs spaceman: unexpected object type {otype:#x}"
        )));
    }
    let block_size = u32::from_le_bytes(buf[32..36].try_into().unwrap());
    let blocks_per_chunk = u32::from_le_bytes(buf[36..40].try_into().unwrap());
    let main_block_count = u64::from_le_bytes(buf[48..56].try_into().unwrap());
    let main_chunk_count = u64::from_le_bytes(buf[56..64].try_into().unwrap());
    let main_cib_count = u32::from_le_bytes(buf[64..68].try_into().unwrap());
    let main_cab_count = u32::from_le_bytes(buf[68..72].try_into().unwrap());
    let main_free_count = u64::from_le_bytes(buf[72..80].try_into().unwrap());
    let cib_addr_off = u32::from_le_bytes(buf[80..84].try_into().unwrap()) as usize;
    if cib_addr_off + 8 > buf.len() {
        return Err(crate::Error::InvalidImage(format!(
            "apfs spaceman: sm_addr_offset {cib_addr_off} past block end"
        )));
    }
    let cib_paddr = u64::from_le_bytes(buf[cib_addr_off..cib_addr_off + 8].try_into().unwrap());
    Ok(DecodedSpaceman {
        block_size,
        blocks_per_chunk,
        main_block_count,
        main_chunk_count,
        main_cib_count,
        main_cab_count,
        main_free_count,
        cib_paddr,
    })
}

/// Decode the chunk_info entries inside a CIB block.
#[cfg(test)]
pub(super) fn decode_cib_entries(buf: &[u8]) -> Result<Vec<DecodedChunkInfo>> {
    if buf.len() < 40 {
        return Err(crate::Error::InvalidImage(
            "apfs CIB: block too short".into(),
        ));
    }
    let otype = u32::from_le_bytes(buf[24..28].try_into().unwrap());
    if otype & 0x0000_ffff != OBJECT_TYPE_SPACEMAN_CIB {
        return Err(crate::Error::InvalidImage(format!(
            "apfs CIB: unexpected object type {otype:#x}"
        )));
    }
    let count = u32::from_le_bytes(buf[36..40].try_into().unwrap()) as usize;
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let off = 40 + i * 32;
        if off + 32 > buf.len() {
            return Err(crate::Error::InvalidImage(
                "apfs CIB: chunk_info_t past block end".into(),
            ));
        }
        out.push(DecodedChunkInfo {
            addr: u64::from_le_bytes(buf[off + 8..off + 16].try_into().unwrap()),
            block_count: u32::from_le_bytes(buf[off + 16..off + 20].try_into().unwrap()),
            free_count: u32::from_le_bytes(buf[off + 20..off + 24].try_into().unwrap()),
            bitmap_addr: u64::from_le_bytes(buf[off + 24..off + 32].try_into().unwrap()),
        });
    }
    Ok(out)
}

/// Lightweight decoded view of one `chunk_info_t`.
#[cfg(test)]
#[derive(Debug)]
pub(super) struct DecodedChunkInfo {
    pub addr: u64,
    pub block_count: u32,
    pub free_count: u32,
    pub bitmap_addr: u64,
}

/// Count the set bits in a bitmap buffer covering the first
/// `chunk_blocks` bits. (Bits past `chunk_blocks` are ignored.)
#[cfg(test)]
pub(super) fn count_used_bits(bmap: &[u8], chunk_blocks: u32) -> u32 {
    let mut n: u32 = 0;
    for bit in 0..chunk_blocks as usize {
        if bmap[bit / 8] & (1 << (bit % 8)) != 0 {
            n += 1;
        }
    }
    n
}
